Add store locator
mapbox/public-tools-and-demos pull request #3
Opened 2024-09-06 19:26 UTC by AndrewSepic

2024-10-14 20:23 UTC, chriswhong requested changes
I've left a lot of suggestions to clarify comments, and some requests to rename components and split them into separate files.

Can we also run `prettier` on this project? (I would like to have prettier run on commit in this repo, but we can handle that later)

I have some other requests for the UI/UX which I'll communicate in a different channel.

2024-10-14 20:23 UTC, chriswhong commented on projects/demo-store-locator/src/Context/AppContext.jsx
> +  // The data returned from the visible viewport of the map. Rendered in LocationListing
```suggestion
  // The store data in the current map viewport. Rendered in LocationListing, updated whenever the viewport changes
```

2024-10-14 20:23 UTC, chriswhong commented on projects/demo-store-locator/src/LocationListing.jsx
> +// The LocationListing component renders GeoJSON feature information retrieved by
Can we rename this to `CardList`?

2024-10-14 20:23 UTC, chriswhong commented on projects/demo-store-locator/src/Map/index.jsx
> +      style: 'mapbox://styles/examples/cm0foo08s01tn01qq2dzccr6i',
```suggestion
      // this is a custom style, created with store location data loaded via Mapbox Tiling Service and styled in Mapbox Studio.
      style: 'mapbox://styles/examples/cm0foo08s01tn01qq2dzccr6i', 
```

2024-10-14 20:23 UTC, chriswhong commented on projects/demo-store-locator/src/Map/index.jsx
> +    // Change the cursor to a pointer when the mouse is over a feature in the layer.
```suggestion
    // Change the cursor to a pointer when the mouse is over a feature in the store-locations layer.  
```

2024-10-14 20:23 UTC, chriswhong commented on projects/demo-store-locator/src/layout.jsx
> +  description: 'Generated by create next app'
```suggestion
  description: 'A demo store locator app showcasing various Mapbox products and techniques.'
```

2024-10-16 14:42 UTC, AndrewSepic commented on projects/demo-components/package.json
> +    "react-markdown": "^9.0.1",
I've removed these from 'demo-store-locator'.  To remove them from `demo-real-estate`, that project needs to get some minor updates to remove their components, import the new components and adapt the display to be consistent with the toggleable layout.  I'd like to PR that in separately, after this is merged.

2024-10-16 15:02 UTC, AndrewSepic commented on projects/demo-store-locator/src/LocationListing.jsx
> +// The LocationListing component renders GeoJSON feature information retrieved by
Sure.

2024-10-16 17:09 UTC, chriswhong approved these changes
Looks great! Glad to see this get across the finish line!

2024-10-16 18:25 UTC, merged